ARG FLINK_IMAGE=__FLINK_BASE_IMAGE__
FROM ${FLINK_IMAGE}

USER root
RUN apt-get update \
    && apt-get install --yes --no-install-recommends python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*
COPY __PYTHON_PROJECT__/ /opt/flink/usrlib/python/
RUN if [ -f /opt/flink/usrlib/python/requirements.txt ]; then \
      python3 -m pip install --no-cache-dir -r /opt/flink/usrlib/python/requirements.txt; \
    fi \
    && chown -R flink:flink /opt/flink/usrlib/python
USER flink
