apiVersion: __FLINK_API_VERSION__
kind: FlinkStateSnapshot
metadata:
  name: __SNAPSHOT_NAME__
  namespace: __NAMESPACE__
spec:
  jobReference:
    kind: __FlinkDeployment_OR_FlinkSessionJob__
    name: __JOB_RESOURCE_NAME__
  savepoint:
    disposeOnDelete: false
    formatType: CANONICAL
